{
 "title": "HTTP Requests Monitoring",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "1m",
 "panels": [
  {
   "title": "Endpoints",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(http_requests_received_total) by (endpoint)",
     "legendFormat": "{{ endpoint }}"
    }
   ]
  },
  {
   "title": "Status Codes",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum(http_requests_received_total) by (code)",
     "legendFormat": "{{ code }}"
    }
   ]
  },
  {
   "title": "Success Rate",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 10, "w": 6, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "sum(http_requests_received_total{code=\"200\"}) / sum(http_requests_received_total) * 100",
     "legendFormat": "Success"
    },
    {
     "expr": "(sum(http_requests_received_total) - sum(http_requests_received_total{code=\"200\"})) / sum(http_requests_received_total) * 100",
     "legendFormat": "Fail"
    }
   ]
  }
 ]
}